name: mortuary
description: "Mortuary App for death reporting on Hajj"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.1
  flutter_native_splash: ^2.3.7
  flutter_svg: ^2.0.9
  get: ^4.6.6
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  file_picker: ^6.1.1
  image_cropper: ^4.0.1
  internet_connection_checker_plus: ^1.0.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_secure_storage: ^8.0.0


  ########## MAPS ######
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  ### For Location NAme
  geocoding: ^2.1.1
  map_launcher: ^3.3.0
##########################


  #location: ^5.0.3
  #flutter_google_places: ^0.3.0


  firebase_messaging: any
  flutter_local_notifications: ^17.1.0
  flutter_timezone: ^1.0.8
  firebase_core: ^2.13.1
  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.4
  fluttertoast: ^8.0.8
  socket_io_client: ^2.0.3+1
  web_socket_client: any
  wave: ^0.2.2
  pin_code_fields: ^7.3.0
  mobile_scanner: ^4.0.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/img_app_icon.png
  # branding: assets/icons/3x/branding_light.png
  android: true
  ios: true
  # color_dark: 1F1B16
  color: "#F1FFEA"
  fullscreen: true
  android_12:
    image: assets/images/img_app_icon.png
    # branding: assets/icons/3x/branding_light.png
    # color_dark: 1F1B16
    color: "#F1FFEA"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/raw/
    - assets/flags/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
